[package]
name = "foo"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
bytes = "0.4"
hyper = "0.11"
futures = "0.1"
scheduled-thread-pool = "0.1"
tokio-openssl = "0.1.3"
tokio-core = "0.1"
tokio-io-timeout = "0.1"
tokio-proto = "0.1"
openssl = "0.9"
